//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportApp.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fuel
    {
        public int ID { get; set; }
        public string Марка { get; set; }
        public Nullable<int> Норма { get; set; }
        public Nullable<int> Факт { get; set; }
    }
}
