//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportApp.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class WayList
    {
        public int Номер { get; set; }
        public string Дата_выдачи { get; set; }
        public string Марка { get; set; }
        public string Госномер { get; set; }
        public string Водитель_1 { get; set; }
        public string Водитель_2 { get; set; }
        public string Маршрут { get; set; }
        public Nullable<int> Объем_бака { get; set; }
        public string Тип_топлива { get; set; }
        public Nullable<int> Остаток_в_баке { get; set; }
        public Nullable<int> Колво_заправл_топлива { get; set; }
        public Nullable<int> выдача_ПЛ { get; set; }
        public Nullable<int> Сдача_ПЛ { get; set; }
    }
}
